apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vrijbrp.fullname" . }}-nginx
  labels:
    {{- include "vrijbrp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "vrijbrp.nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "vrijbrp.nginx.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ template "fullname" . }}-personen-nginx
      containers:
        - name: {{ include "vrijbrp.fullname" . }}-nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "docker.io/nginx:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
           initialDelaySeconds: 5
           httpGet:
             path: /personen/rest/v2/info
             port: http
          livenessProbe:
           initialDelaySeconds: 30
           httpGet:
             path: /personen/rest/v2/info
             port: http
          env:
            - name: NGINX_HOST
              value: {{ include "vrijbrp.fullname" . }}-backend
            - name: NGINX_PORT
              value: "80"
          volumeMounts:
            - name: nginx-config
              subPath: default.conf.template
              readOnly: true
              mountPath: /etc/nginx/templates/default.conf.template
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "vrijbrp.fullname" . }}
  labels:
    {{- include "vrijbrp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vrijbrp.nginx.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-personen-nginx
  labels:
    app.kubernetes.io/name: {{ template "fullname" . }}-personen-nginx
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  default.conf.template: |
    server {
      location /personen {
         proxy_pass http://${NGINX_HOST}:${NGINX_PORT}/personen;
         proxy_set_header       Host   $http_host;
         client_max_body_size   100M;
      }
    }

