apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "fullname" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  applicatie.properties: |
    app_db_name=postgres
    app_db_server={{ .Values.global.postgresql.host }}
    app_db_port={{ .Values.global.postgresql.port }}
    app_db_schema=
    app_db_username={{ .Values.global.postgresql.username }}
    app_db_password={{ .Values.global.postgresql.password }}
    app_db_sid=personen
    crypt.version1.key=ThisIsTheDefaultHash
    license.key={{ .Values.security.license }}
    loglevel={{ .Values.global.settings.logLevel }}
    c_gem={{ .Values.global.settings.gemeentecode }}
    s_gem={{ .Values.global.settings.gemeentenaam }}
    s_app=vrijBRP Balie
    PARM_java_ple_server_url=http://{{ .Release.Name }}-balie-ws-backend/personen-ws

