apiVersion: v1
kind: Service
metadata:
  name: {{ include "vrijbrp.fullname" . }}-backend
  labels:
    {{- include "vrijbrp.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "vrijbrp.selectorLabels" . | nindent 4 }}
