apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vrijbrp.fullname" . }}
  labels:
    {{- include "vrijbrp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "vrijbrp.ws.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "vrijbrp.ws.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: config
        secret:
          secretName: {{ template "fullname" . }}
      - name: log4j
        configMap:
          name: {{ template "fullname" . }}
      containers:
        - name: {{ include "vrijbrp.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
           initialDelaySeconds: 5
           httpGet:
             path: /personen-ws/rest/v2/info
             port: http
          livenessProbe:
           initialDelaySeconds: 30
           httpGet:
             path: /personen-ws/rest/v2/info
             port: http
          volumeMounts:
            - name: config
              mountPath: /usr/local/tomcat/procura/applicaties/personen-ws/config/applicatie.properties
              subPath: applicatie.properties
            - name: log4j
              readOnly: true
              mountPath: /usr/local/tomcat/lib/log4j.properties
              subPath: log4j.properties
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
