apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "fullname" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  applicatie.properties: |
    app_db_name=postgres
    app_db_server={{ .Values.global.postgresql.host }}
    app_db_port={{ .Values.global.postgresql.port }}
    app_db_schema=
    app_db_username={{ .Values.global.postgresql.username }}
    app_db_password={{ .Values.global.postgresql.password }}
    app_db_sid={{ .Values.global.postgresql.prefix }}_personen_ws
    c_gem={{ .Values.global.settings.gemeentecode }}
    s_gem={{ .Values.global.settings.gemeentenaam }}
    s_app=vrijBRP Balie WS
    proweb.authentication=http://{{ .Release.Name }}-balie-backend/personen
    procura.endpoint=https://burgerzaken.procura.nl
    # default parameters in database
    PARM_procura.db.tns-admin-dir=
    PARM_procura.db.custom-url=
    PARM_procura.db.custom-driver=
    PARM_procura.db.db=postgres
    PARM_procura.db.sid={{ .Values.global.postgresql.prefix }}_rvig_testdb
    PARM_procura.db.server={{ .Values.procura.database.host }}
    PARM_procura.db.port={{ .Values.procura.database.port }}
    PARM_procura.db.username={{ .Values.procura.database.username }}
    PARM_procura.db.password={{ .Values.procura.database.password }}
    PARM_procura.db.connections.read.min=2
    PARM_procura.db.connections.read.max=5
