{{- if .Values.imageRegistry }}
apiVersion: v1
kind: Secret
metadata:
  name: vrijbrp-private-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imageRegistrySecret" . }}
{{- end }}