{{- if .Values.imageRegistry }}
apiVersion: v1
kind: Secret
metadata:
  name: vrijbrp-private-registry
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imageRegistrySecret" . }}
{{- end }}