apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-balie
  labels:
    app.kubernetes.io/name: {{ template "fullname" . }}-balie
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  applicatie.properties: |
    app_db_name=postgres
    app_db_server={{ .Values.postgresql.host }}
    app_db_port={{ .Values.postgresql.service.port }}
    app_db_schema=
    app_db_username={{ .Values.postgresql.username }}
    app_db_password={{ .Values.postgresql.password }}
    app_db_sid=personen
    crypt.version1.key=ThisIsTheDefaultHash
    license.key={{ .Values.security.license }}
    loglevel={{ .Values.settings.logLevel }}
    s_app=vrijBRP Balie
    c_gem={{ .Values.settings.gemeentecode }}
    s_gem={{ .Values.settings.gemeentenaam }}
    PARM_java_ple_server_url=http://{{ include "vrijbrp.fullname" . }}-balie-ws-backend/personen-ws

