{{- $postgresqlServiceName := include "postgresql.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-balie
  labels:
    app.kubernetes.io/name: {{ template "fullname" . }}-balie
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  applicatie.properties: |
    #Tue Mar 16 13:27:00 GMT 2021
    app_db_name=postgres
    app_db_password={{ .Values.postgresql.postgresqlPassword }}
    app_db_port={{ .Values.postgresql.service.port }}
    app_db_schema=
    {{ if .Values.postgresql.enabled }}
    app_db_server={{ $postgresqlServiceName }}
    {{ else }}
    app_db_server={{ .Values.postgresql.host }}
    {{ end }}
    app_db_username={{ .Values.postgresql.postgresqlUsername }}
    app_db_sid=personen
    c_gem={{ .Values.settings.gemeentecode }}
    crypt.version1.key=ThisIsTheDefaultHash
    license.key={{ .Values.security.license }}
    loglevel={{ .Values.settings.logLevel }}
    s_app=vrijBRP Balie
    s_gem={{ .Values.settings.gemeentenaam }}

