apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "vrijbrp.fullname" . }}-postgres-init-job
  labels:
    {{- include "vrijbrp.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  manualSelector: true
  selector:
    matchLabels:
      {{- include "vrijbrp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vrijbrp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: postgres-init-job
        image: docker-repo.procura.nl/vrijbrp/postgres-init:1.0.0
        imagePullPolicy: IfNotPresent
        env:
          - name: "PGHOST"
            value: {{ .Values.global.postgresql.host | quote }}
          - name: "PGPORT"
            value: {{ .Values.global.postgresql.port | quote }}
          - name: "PGUSER"
            value: {{ .Values.global.postgresql.username | quote }}
          - name: "PGPASSWORD"
            value: {{ .Values.global.postgresql.password | quote }}
      restartPolicy: OnFailure
  backoffLimit: 2