apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-env
  labels:
    app.kubernetes.io/name: {{ template "fullname" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  PGHOST: {{ .Values.global.postgresql.host | quote }}
  PGPORT: {{ .Values.global.postgresql.port  | quote }}
  PGUSER: {{ .Values.global.postgresql.username  | quote }}
  PGPASSWORD: {{ .Values.global.postgresql.password  | quote }}