{{- if .Values.imagePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: vrijbrp-private-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}