apiVersion: v1
entries:
  postgresql:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 11.11.0
    created: "2021-04-09T16:17:24.382213+02:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.x.x
    description: Chart for PostgreSQL, an object-relational database management system
      (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: 9b7ac83baa2b4736891c044cfe1c5f7608d8c94dc3fc008aea5571bd1f8b297f
    home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    - https://www.postgresql.org/
    urls:
    - charts/postgresql-10.3.13.tgz
    version: 10.3.13
  vrijbrp:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-04-09T16:17:24.3692108+02:00"
    dependencies:
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.3.13
    description: A Helm chart for Kubernetes
    digest: f58ba7a0e9d54e1d6bf27a05fff7de22a038abcbe2dc57d37666f2762bd78c10
    name: vrijbrp
    type: application
    urls:
    - vrijbrp-0.1.0.tgz
    version: 0.1.0
generated: "2021-04-09T16:17:24.3547972+02:00"
