apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "fullname" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  application.properties: |
    server.servlet.context-path=/haal-centraal-brp-bevragen
    server.use-forward-headers=true
    procura.personrecordsource.url=http://{{ .Release.Name }}-balie-ws-backend/personen-ws/rest