apiVersion: v1
kind: Service
metadata:
  name: {{ include "vrijbrp.fullname" . }}-backend
  labels:
    {{- include "vrijbrp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vrijbrp.hcbrp.selectorLabels" . | nindent 4 }}
